spring:
  application:
    name: license-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone :  http://localhost:8761/eureka-server/eureka
    fetch-registry: true

management:
  endpoint:
    info:
      enabled: true
server:
  port: 8080
