spring:
  profiles:
    active: vault
  application:
    name: configserver
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.01
          kvVersion: 2
server:
  port: 8701
